### ISSUE TITLE
[Bug] When sending all subjects in one run, disabled keys renders

### ISSUE THREAD

**Issue by igormukhingmailcom** [synolia/SyliusMailTesterPlugin#15]
**Describe the bug**
It takes all forms `'form_every_subjects' => $this->formTypeResolver->getAllFormTypes(),`  without filtering if some key exists.

**To Reproduce**
1. Remove some key from email configuration (you should have form type implemented for that email key)
2. Choose all subjects at admin
3. See form of that removed key not disappeared

**Comment by oallain** [comment]
Hello @igormukhingmailcom 

We have fix this issue 💪🏼 
Now we use parameter `%sylius.mailer.emails%` to filter mail.

Please update to v2 of plugin to take advantage of this fix. 🚀 

Regards

**Comment by igormukhingmailcom** [comment]
Cool, thanks ;)
