### ISSUE TITLE
Love this plugin, could we upgrade it to Sylius 1.9

### ISSUE THREAD

**Issue by loevgaard** [synolia/SyliusMailTesterPlugin#19]
Hi there

Thanks for this great plugin. I love it <3

Is it possible to upgrade it to Sylius 1.9? :-)

**Comment by oallain** [comment]
Hello @loevgaard ,

Thank you for this feedback 😍 

We are updating our plugins, to be compatible with Sylius 1.9, but we have not yet addressed this one.
I hope to do it quickly, but I don't know how soon.

Bests,

**Comment by loevgaard** [comment]
Thank you for the response :)

**Comment by oallain** [comment]
Hello @loevgaard ,

New Release [v2.0.0](https://github.com/synolia/SyliusMailTesterPlugin/releases/tag/v2.0.0) is done 🎉

**Comment by loevgaard** [comment]
Thank you, Olivier ❤️
