### ISSUE TITLE
[Bug] Notice: Trying to access array offset on value of type null

### ISSUE THREAD

**Issue by igormukhingmailcom** [synolia/SyliusMailTesterPlugin#5]
**Describe the bug**
At `MailTesterController.php (line 52)` we're trying to check subjects array item without checking is that key exists which is causing an error.

**To Reproduce**
1. Go to 'http://localhost/admin/mail/tester'
2. See error

**Expected behavior**
Check subjects key

**Screenshots**
![image](https://user-images.githubusercontent.com/6544038/85443806-59899000-b59a-11ea-8ebb-7db51c681917.png)

**Comment by igormukhingmailcom** [comment]
I will provide PR now

**Comment by oallain** [comment]
Thanks a lot for issue and PR @igormukhingmailcom 👌
