### ISSUE TITLE
[Bug] New fields from overriden entities not available

### ISSUE THREAD

**Issue by igormukhingmailcom** [synolia/SyliusMailTesterPlugin#8]
**Describe the bug**
If I override, say, `Sylius\Core\Model\Order` entity (so it have name `App\Entity\Order`) and add new field to it, say, `field1`, I can't access that new field at email template, as `Order::class` is hardcoded to `Sylius\Core\Model\Order`, but `%sylius.model.order.class%` should be used.

**To Reproduce**
1. Override some entity and add new field
2. Try to access new field at email template
3. See error

I will provide PR now

**Comment by oallain** [comment]
Thanks @igormukhingmailcom for used this Plugin and make issues and even more PR of patches :tada: 

I juste created a new release with your work : https://github.com/synolia/SyliusMailTesterPlugin/releases/tag/v1.1.0
